services:
  # Service chính với warm up tích hợp
  ai-legal-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_SERVER_NOFILE=65536
    volumes:
      # Mount data directory để persist dữ liệu
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 15s
      retries: 8
      start_period: 90s  # Increased for double warm up time
    restart: unless-stopped
    networks:
      - ai-legal-network

networks:
  ai-legal-network:
    driver: bridge

volumes:
  ai-legal-data:
    driver: local
