services:
  # Service chính với warm up tích hợp
  ai-legal-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_SERVER_NOFILE=65536
    volumes:
      # Mount data directory để persist dữ liệu
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 8
      start_period: 120s  # Increased for warmup + smoke test time
    restart: unless-stopped
    networks:
      - ai-legal-network
    # Default sử dụng smoke test
    command: ["/app/scripts/start_with_smoke_test.sh"]

networks:
  ai-legal-network:
    driver: bridge

volumes:
  ai-legal-data:
    driver: local
