[tool.black]
line-length = 88
target-version = ['py310']
include = '\.py$'
extend-exclude = '''
/(
  \.venv
  | \.git
  | \.tox
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 880
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
src_paths = ["."]

[tool.pylint]
max-line-length = 1000
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "invalid-name",
    "unused-variable",
    "wrong-import-position",
    "too-many-branches",
    "too-many-statements",
    "duplicate-code",
    "redefined-outer-name"
]
