version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: logs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  src:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
    propagate: False  # Prevent duplicate logging

  scripts:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
    propagate: False

  app:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
    propagate: False  # Không propagate để tránh duplicate logs

  app.rag:
    level: INFO
    handlers: []  # Không cần handlers vì đã được thêm trong get_logger_app
    propagate: False  # Không propagate để tránh duplicate logs

  app.retrieve:
    level: INFO
    handlers: []  # Không cần handlers vì đã được thêm trong get_logger_app
    propagate: False  # Không propagate để tránh duplicate logs

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]
